import React from 'react'
import DynamicForm from '../../Feedback/components/DynamicForm'
import FormBuilder from './FormBuilder'

const DynamicFBForm: React.FC = () => {
  // Replace this with the JSON data generated by the form builder

  return (
    <div>
      <div>
        <h1>Dynamic Form</h1>
        <DynamicForm />
        <hr />
        <h1>Form Builder</h1>
        <FormBuilder />
      </div>
    </div>
  )
}

export default DynamicFBForm
